// Decision support. Turns the published results of the seven suites, together with the live site context
// (seabed temperature and depth, prices, carbon price, grid carbon, interest and inflation), into ranked,
// reasoned recommendations and a sustainability scorecard. Pure functions: no DOM, no network.
//
// Every recommendation states the finding (with the numbers), the action, the expected benefit, the
// benchmark it was judged against, where to act, and a literature topic for live evidence look-up.

const fin = (x) => typeof x === 'number' && Number.isFinite(x);
const clamp = (x, a, b) => Math.min(b, Math.max(a, x));
const f = (x, d = 2) => (fin(x) ? (Math.abs(x) >= 100 ? x.toFixed(0) : Math.abs(x) >= 10 ? x.toFixed(1) : x.toFixed(d)) : '–');
const M = (x) => (fin(x) ? (Math.abs(x) >= 1e9 ? (x / 1e9).toFixed(2) + ' bn$' : (x / 1e6).toFixed(1) + ' M$') : '–');
const BOE_PER_SM3_OIL = 6.2898, SM3_GAS_PER_BOE = 164;

/** Reference ranges used as benchmarks. Typical published industry practice; planning guides, not limits of law or of any code. */
export const BENCHMARKS = {
  cooldown: { label: 'Cooldown time to hydrate temperature', unit: 'h', good: 12, typical: 8, poor: 4, higherIsBetter: true, basis: 'Deep-water flowlines are commonly designed for 8–12 h or more between shut-in and the first point reaching hydrate temperature, so that a no-touch period and the preservation sequence both fit.' },
  hydrateMargin: { label: 'Arrival temperature above hydrate temperature', unit: '°C', good: 10, typical: 5, poor: 0, higherIsBetter: true, basis: 'A margin of 3–5 °C on the hydrate curve is the usual minimum for steady production; turndown and uncertainty in the fluid consume the rest.' },
  erosional: { label: 'Velocity / erosional velocity', unit: '–', good: 0.6, typical: 0.8, poor: 1.0, basis: 'API RP 14E erosional velocity (C-factor) screening; solids-laden service is assessed with a particle-impact model instead.' },
  stress: { label: 'Highest stress utilisation', unit: '–', good: 0.72, typical: 0.85, poor: 1.0, basis: 'Design factors of pipeline codes (for example 0.72 on hoop stress for liquid lines in ASME B31.4) leave this much of the yield strength in reserve.' },
  corrosion: { label: 'Internal corrosion rate', unit: 'mm/y', good: 0.05, typical: 0.1, poor: 0.3, basis: 'Carbon-steel lines with inhibition are normally managed to about 0.1 mm/y or less; several tenths of a millimetre per year consumes a 3 mm allowance within a decade.' },
  pof: { label: 'Annual probability of failure', unit: '1/y', good: 1e-5, typical: 1e-4, poor: 1e-3, basis: 'Target failure probabilities for pipelines by safety class are of the order of 10⁻³ (low) to 10⁻⁵ (high) per year for ultimate limit states.' },
  uptime: { label: 'Production uptime', unit: '%', good: 97, typical: 94, poor: 88, higherIsBetter: true, basis: 'Subsea tie-backs typically achieve 92–97 % production efficiency; flow-assurance stoppages are one of the larger controllable losses.' },
  surge: { label: 'Liquid surge / slug-catcher volume', unit: '–', good: 0.5, typical: 0.8, poor: 1.0, basis: 'The receiving vessel should hold the largest slug or pigging surge with margin for level control; above 1.0 the vessel trips on high level.' },
  carbon: { label: 'Carbon intensity of production', unit: 'kgCO₂e/boe', good: 8, typical: 18, poor: 35, basis: 'Reported upstream intensities average roughly 15–20 kgCO₂e per barrel of oil equivalent worldwide, with the best-performing assets below 10.' },
  energy: { label: 'Flow-assurance energy use', unit: 'kWh/boe', good: 1, typical: 4, poor: 12, basis: 'Heating, boosting and compression duties attributed to transport; planning guide for comparing options within one study.' },
  chemicals: { label: 'Hydrate inhibitor use', unit: 'L/boe', good: 0.3, typical: 1.5, poor: 5, basis: 'Continuous thermodynamic inhibition of a wet system uses of the order of a litre of inhibitor per barrel produced before regeneration; insulation or low-dosage inhibitors reduce it sharply.' },
  utc: { label: 'Unit technical cost', unit: '$/boe', good: 15, typical: 25, poor: 40, basis: 'Indicative range for sanctioned subsea tie-backs and deep-water developments; the break-even against the current oil price is the test that matters.' },
  life: { label: 'Remaining life / required life', unit: '–', good: 1.5, typical: 1.0, poor: 0.5, higherIsBetter: true, basis: 'Wall-loss and fatigue life compared with the remaining project life; below 1.0 the line needs mitigation, repair or replacement before the end of the project.' },
};

/** 0–100 score from a benchmark (100 at "good" or better, 50 at "typical", 0 at "poor" or worse). */
export function score(value, b) {
  if (!fin(value)) return null;
  const s = b.higherIsBetter ? -1 : 1, v = s * value, g = s * b.good, t = s * b.typical, p = s * b.poor;
  if (v <= g) return 100;
  if (v >= p) return 0;
  return v <= t ? 100 - (50 * (v - g)) / (t - g) : 50 - (50 * (v - t)) / (p - t);
}
const rate = (s) => (s === null ? 'not assessed' : s >= 80 ? 'strong' : s >= 55 ? 'acceptable' : s >= 30 ? 'needs attention' : 'weak');
const logScore = (v, b) => (fin(v) && v > 0 ? score(Math.log10(v), { good: Math.log10(b.good), typical: Math.log10(b.typical), poor: Math.log10(b.poor) }) : null);

/** Shared facts assembled from whatever suites have been run. */
export function facts(outputs = {}, site = {}, fluid = {}) {
  const o = outputs, d = site.data || {}, r = o.pvt?.rates;
  const qOil = fin(r?.qOilStd) ? r.qOilStd : fluid.rateBasis === 'oil' || !fluid.rateBasis ? +fluid.qOil || 0 : 0, qGas = fin(r?.qGasStd) ? r.qGasStd : fluid.rateBasis === 'gas' ? (+fluid.qGas || 0) * 1e6 : 0;
  const boed = qOil * BOE_PER_SM3_OIL + qGas / SM3_GAS_PER_BOE; // barrels of oil equivalent per day
  const tHyd = o.flow?.profile?.tHyd, tOutHyd = Array.isArray(tHyd) && tHyd.length ? tHyd[tHyd.length - 1] : null;
  const margin = fin(o.flow?.tOut) && fin(tOutHyd) ? o.flow.tOut - tOutHyd : fin(o.flow?.maxSubcooling) ? -o.flow.maxSubcooling : null;
  const power = [o.ops?.heatingPower, o.net?.pumpPower, o.net?.compressorPower].filter(fin).reduce((a, b) => a + b, 0);
  const inhRate = [o.ops?.inhibitorRate, o.solids?.inhibitorRate].find(fin) ?? null; // m³/d
  const life = fin(o.econ?.projectLife) ? o.econ.projectLife : 20;
  const util = [o.integ?.hoopUtil, o.integ?.vmUtil, o.integ?.collapseUtil].filter(fin); // the buckling ratio is a design-management flag, not a strength utilisation
  return { o, d, fluid, qOil, qGas, boed, margin, power, inhRate, life, maxUtil: util.length ? Math.max(...util) : null, oilPrice: fin(d.oilPrice) ? d.oilPrice : null, catcher: fin(o.net?.slugCatcherVol) ? o.net.slugCatcherVol : null };
}

const R = (priority, area, title, why, action, benefit, goTo, basis, topic, suites) => ({ priority, area, title, why, action, benefit, goTo, basis, topic, suites });

/** All rules. Each returns zero or more recommendations from the facts. */
function rules(F) {
  const { o, d, fluid } = F, out = [], B = BENCHMARKS, fl = o.flow, so = o.solids, op = o.ops, ig = o.integ, ec = o.econ, nt = o.net, pv = o.pvt;
  // ---- hydrates
  if (fl && fin(fl.maxSubcooling) && fl.maxSubcooling > 0) out.push(R(1, 'Hydrates', 'The line runs inside the hydrate region in steady production', `The fluid is up to ${f(fl.maxSubcooling, 1)} °C colder than the hydrate temperature over ${fin(fl.hydrateLength) ? f(fl.hydrateLength / 1000, 1) + ' km' : 'part'} of the line (arrival ${f(fl.tOut, 1)} °C).`, 'Add insulation or raise the rate to keep the fluid warm, or inhibit continuously; compare the options by lifecycle cost in suite 7.', 'Removes the largest single cause of unplanned deep-water shutdowns.', 'solids', B.hydrateMargin.basis, 'gas hydrate plug prevention subsea flowline insulation inhibition', ['flow', 'solids', 'ops', 'econ']));
  else if (fin(F.margin) && F.margin < B.hydrateMargin.typical) out.push(R(2, 'Hydrates', 'The hydrate margin at arrival is thin', `Arrival temperature is only ${f(F.margin, 1)} °C above the hydrate temperature; a modest turndown or a colder season removes it.`, 'Find the minimum rate that keeps the margin in the operating envelope of suite 5 and add insulation if that rate is too close to plan.', 'Keeps normal turndown outside the hydrate region.', 'ops', B.hydrateMargin.basis, 'minimum flow rate hydrate formation subsea tieback turndown', ['flow', 'ops']));
  if (so) {
    if (fin(so.hydrateRisk) && so.hydrateRisk > 0.5) out.push(R(1, 'Hydrates', 'A hydrate plug is likely in the assessed scenario', `Risk index ${f(so.hydrateRisk)}${fin(so.plugTime) ? `; a plug is predicted after about ${f(so.plugTime, 1)} h` : ''}${fin(so.plugX) ? ` near ${f(so.plugX / 1000, 1)} km` : ''}${fin(so.plugProbability) ? ` (probability ${f(100 * so.plugProbability, 0)} %)` : ''}.`, fin(so.inhibitorRequired) ? `Treat the water phase to ${f(so.inhibitorRequired, 0)} wt % inhibitor before entering this scenario, or keep the shutdown shorter than the cooldown time.` : 'Inhibit before entering this scenario or shorten the exposure.', 'Avoids a blockage whose remediation takes days to weeks of lost production.', 'solids', 'Kinetic hydrate formation, deposition and plugging model of suite 4.', 'hydrate plug formation restart shutdown oil dominated flowline', ['solids', 'ops']));
    if (fin(so.inhibitorRequired) && so.inhibitorRequired > (+fluid.inhWt || 0) + 1 && so.inhibitorRequired < 90) out.push(R(fin(so.hydrateRisk) && so.hydrateRisk > 0.15 ? 1 : 2, 'Hydrates', 'The inhibitor concentration in the water is below what the coldest condition needs', `${f(so.inhibitorRequired, 0)} wt % is required against ${f(+fluid.inhWt || 0, 0)} wt % in the case${fin(so.inhibitorRate) ? `; that is about ${f(so.inhibitorRate, 1)} m³/d of inhibitor` : ''}.`, 'Set the dose on the Case page (or in suite 5) and re-run; check that the injection system and the storage can deliver it.', 'Moves the hydrate curve below the lowest fluid temperature with margin.', 'ops', 'Thermodynamic inhibition by the water-activity (Nielsen–Bucklin type) relation, checked against the hydrate model of suite 1.', 'methanol MEG hydrate inhibitor dosage calculation subsea', ['solids', 'ops', 'pvt']));
    if (fin(so.blockage) && so.blockage > 0.1) out.push(R(so.blockage > 0.3 ? 1 : 2, 'Solids', 'Deposits are restricting the bore', `${f(100 * so.blockage, 0)} % of the flow area is lost at the worst point (effective bore ${fin(so.effectiveId) ? f(so.effectiveId * 1000, 0) + ' mm' : '–'}).`, 'Pig the line, then set a pigging interval from the growth rate; the restriction is fed back to the flow solution in the integrated run.', 'Restores pressure drop and capacity.', 'solids', 'Deposit growth and effective-diameter model of suite 4.', 'pipeline deposit pigging frequency wax hydrate restriction', ['solids', 'flow', 'ops']));
    if (fin(so.piggingInterval) && so.piggingInterval < 7) out.push(R(2, 'Wax', 'Wax builds up fast enough to need pigging more than weekly', `A thickness limit is reached in about ${f(so.piggingInterval, 1)} days${fin(so.waxRate) ? ` (${f(so.waxRate, 2)} mm/d at the worst point)` : ''}.`, 'Keep the wall above the wax appearance temperature with more insulation, or assess a wax inhibitor; compare with the cost of frequent pigging in suite 7.', 'Fewer pig runs and less deferred production.', 'econ', 'Molecular-diffusion wax deposition model of suite 4.', 'wax deposition subsea pipeline pigging frequency insulation', ['solids', 'ops', 'econ']));
    if (fin(so.scaleSI) && so.scaleSI > 0.5) out.push(R(2, 'Scale', `${so.scaleMineral || 'Mineral'} scale is predicted`, `The saturation index reaches ${f(so.scaleSI)} (scaling above about 0.5 without inhibitor).`, 'Qualify a scale inhibitor for this water and temperature, inject it upstream of the supersaturated section, and avoid mixing incompatible waters.', 'Prevents hard scale that pigging does not remove.', 'solids', 'Saturation index from ion activities in suite 4.', `${so.scaleMineral || 'barium sulfate'} scale inhibitor oilfield produced water`, ['solids']));
    if (so.asphalteneRisk === 'high') out.push(R(2, 'Asphaltenes', 'The fluid screens as unstable for asphaltenes', 'The de Boer and colloidal-instability screens both place the fluid in the problem region during depressurisation.', 'Commission a depressurisation test on live fluid and plan for dispersant injection downhole if confirmed.', 'Avoids deposits in the tubing and at the choke.', 'solids', 'de Boer plot and colloidal instability index.', 'asphaltene precipitation onset de Boer plot screening', ['solids', 'pvt']));
    if (so.sandBed === true) out.push(R(2, 'Sand', 'Sand settles in the line at this rate', `The mixture velocity is below the critical transport velocity of ${f(so.sandCriticalVelocity)} m/s somewhere along the line.`, 'Raise the rate, reduce the bore of the affected section in the design, or plan regular sand pigging; erosion at the bends is checked in suite 6.', 'Avoids stationary beds that promote under-deposit corrosion and pig sticking.', 'solids', 'Critical solids transport velocity correlations in suite 4.', 'sand transport multiphase pipeline critical velocity bed formation', ['solids', 'integ']));
  }
  if (fin(pv?.wat) && fl && fin(fl.tOut) && fl.tOut < pv.wat) out.push(R(2, 'Wax', 'The fluid arrives below its wax appearance temperature', `Arrival ${f(fl.tOut, 1)} °C against a wax appearance temperature of ${f(pv.wat, 1)} °C.`, 'Quantify the deposition rate and pigging interval in suite 4; consider insulation to move the wax front out of the line.', 'Controls pressure-drop growth and restart risk.', 'solids', 'Wax appearance temperature from the solid–liquid equilibrium of suite 1.', 'wax appearance temperature deposition subsea flowline', ['pvt', 'flow', 'solids']));
  // ---- slugging and hydraulics
  if (fl) {
    if (fl.severeSlugging || fl.slug?.type === 'severe') out.push(R(1, 'Slugging', 'Severe riser slugging is predicted', `The riser base is periodically blocked by liquid${fin(fl.slug?.period) ? ` with a cycle of about ${f(fl.slug.period / 60, 1)} min` : ''}${fin(fl.pInAmplitude) ? ` and inlet-pressure swings of ${f(fl.pInAmplitude, 1)} bar` : ''}${fin(fl.slug?.surge) ? `; each blow-out sends about ${f(fl.slug.surge, 0)} m³ of liquid to the separator` : ''}.`, op && op.slugSuppressed ? `Use the tuned inlet-pressure controller on the topside choke from suite 5 (opening ${f(op.chokeOpening, 0)} %).` : 'Stabilise with active control of the topside choke, riser-base gas lift or a higher rate; tune the controller in suite 5.', 'Removes separator trips, compressor upsets and cyclic loads on the riser.', 'ops', 'Bøe criterion, Pots number and the riser-slugging cycle model of suite 3.', 'severe slugging riser active control topside choke gas lift', ['flow', 'ops', 'integ']));
    else if (fl.slug && fl.slug.type && fl.slug.type !== 'none' && F.catcher && fin(fl.slug.surge) && fl.slug.surge > B.surge.typical * F.catcher) out.push(R(fl.slug.surge > F.catcher ? 1 : 2, 'Slugging', 'Slug volume is close to the capacity of the receiving vessel', `${fl.slug.type} slugs of up to about ${f(fl.slug.surge, 0)} m³ arrive at a vessel holding ${f(F.catcher, 0)} m³ of surge.`, 'Enlarge the slug catcher, add level control with a surge allowance, or reduce slug size with a smaller-bore line or a higher minimum rate.', 'Avoids high-level trips and liquid carry-over to compression.', 'net', B.surge.basis, 'slug catcher sizing hydrodynamic slug volume multiphase pipeline', ['flow', 'net', 'ops']));
    if (fin(fl.erosionalRatio) && fl.erosionalRatio > B.erosional.poor) out.push(R(1, 'Integrity', 'Velocity exceeds the erosional limit', `The highest velocity is ${f(fl.maxVelocity, 1)} m/s, ${f(fl.erosionalRatio)} times the erosional velocity.`, 'Reduce the rate, increase the bore of the fast section (usually the riser top and topside piping) or confirm with the particle-impact erosion model of suite 6.', 'Prevents rapid wall loss at bends and restrictions.', 'integ', B.erosional.basis, 'erosional velocity API RP 14E multiphase sand erosion bends', ['flow', 'integ']));
    if (fin(nt?.designPressure) && fin(fl.pIn) && fl.pIn > 0.9 * nt.designPressure) out.push(R(fl.pIn > nt.designPressure ? 1 : 2, 'Integrity', 'Inlet pressure is close to the design pressure', `${f(fl.pIn, 0)} bara is needed at the inlet against a design pressure of ${f(nt.designPressure, 0)} bara.`, 'Check the pressure-protection philosophy; consider a larger bore, a lower arrival pressure or boosting.', 'Keeps normal operation inside the pressure rating with margin for transients.', 'net', 'Design pressure of the line from suite 2.', 'pipeline design pressure operating margin HIPPS subsea', ['flow', 'net', 'integ']));
    if (fin(nt?.whp) && fin(fl.pIn) && fl.pIn > nt.whp * 1.02) out.push(R(1, 'Production', 'The wells cannot deliver the planned rate against this back-pressure', `The flowline needs ${f(fl.pIn, 0)} bara at its inlet, but the wells deliver the rate only at ${f(nt.whp, 0)} bara or less.`, fin(nt.operatingRate) ? `Plan on about ${f(nt.operatingRate, 0)} Sm³/d from the nodal analysis, or lower the back-pressure (larger bore, lower separator pressure, gas lift or boosting).` : 'Lower the back-pressure or revise the rate.', 'A consistent rate for every downstream calculation.', 'net', 'Inflow performance and vertical-lift nodal analysis of suite 2.', 'nodal analysis flowline back pressure subsea boosting production', ['net', 'flow']));
    if (fin(fl.turndownRate) && fl.turndownRate > 0.6) out.push(R(3, 'Operations', 'The stable operating window is narrow', `Stable flow needs at least ${f(100 * fl.turndownRate, 0)} % of the planned rate.`, 'Plan late-life operation now: slug control, gas lift or a smaller replacement line.', 'Extends field life without flow-assurance stoppages.', 'ops', 'Minimum stable rate from the slugging analysis of suite 3.', 'late life turndown multiphase flowline minimum stable flow rate', ['flow', 'ops']));
  }
  // ---- operations
  if (op) {
    if (fin(op.cooldownTime) && op.cooldownTime < B.cooldown.typical) out.push(R(op.cooldownTime < B.cooldown.poor ? 1 : 2, 'Operations', 'Cooldown time is short', `The coldest point${fin(op.coldSpotX) ? ` (at ${f(op.coldSpotX / 1000, 1)} km)` : ''} reaches hydrate temperature ${f(op.cooldownTime, 1)} h after shut-in${fin(op.noTouchTime) ? `, leaving a no-touch time of ${f(op.noTouchTime, 1)} h` : ''}.`, 'Increase insulation on the governing component (often a jumper, connector or the riser base), or plan an immediate inhibitor displacement; suite 7 finds the thickness of lowest lifecycle cost.', 'Time for operators to diagnose a trip before committing to preservation.', 'econ', B.cooldown.basis, 'subsea flowline cooldown time insulation no-touch time hydrate', ['ops', 'net', 'econ']));
    if (fin(op.blowdownMinT) && op.blowdownMinT < -29) out.push(R(op.blowdownMinT < -46 ? 1 : 2, 'Operations', 'Blowdown chills the fluid below the limit of ordinary carbon steel', `Minimum temperature during depressurisation is ${f(op.blowdownMinT, 0)} °C.`, 'Slow the blowdown (smaller orifice or staged), or confirm that the topside and flare materials are rated for it.', 'Avoids brittle-fracture risk during a routine operation.', 'ops', 'Carbon steel is generally limited to about −29 °C and low-temperature grades to about −46 °C.', 'pipeline depressurisation low temperature Joule Thomson brittle fracture', ['ops', 'integ']));
    if (F.catcher && fin(op.pigSurge) && op.pigSurge > F.catcher) out.push(R(2, 'Operations', 'Pigging surge exceeds the slug-catcher volume', `A pig run delivers about ${f(op.pigSurge, 0)} m³ of liquid against ${f(F.catcher, 0)} m³ of surge capacity.`, 'Reduce the rate while pigging, use a by-pass pig, or pig more often so that less liquid is swept each time.', 'Pigging without tripping the receiving facility.', 'ops', B.surge.basis, 'pigging liquid surge slug catcher bypass pig multiphase', ['ops', 'net']));
    if (fin(op.uptime) && 100 * op.uptime < B.uptime.typical) out.push(R(3, 'Production', 'Uptime is below typical practice', `${f(100 * op.uptime, 1)} % against ${B.uptime.typical}–${B.uptime.good} %${fin(op.deferredVolume) ? `; about ${f(op.deferredVolume, 0)} Sm³ of oil is deferred each year` : ''}.`, 'Rank the causes in the event table of suite 5; shorter restarts and fewer flow-assurance stoppages usually give the cheapest gain.', 'More production from the same asset.', 'ops', B.uptime.basis, 'production efficiency subsea tieback unplanned downtime flow assurance', ['ops', 'econ']));
  }
  // ---- integrity and risk
  if (ig) {
    if (fin(F.maxUtil) && F.maxUtil > 1) out.push(R(1, 'Integrity', 'A stress limit is exceeded', `Highest utilisation ${f(F.maxUtil)} (hoop ${f(ig.hoopUtil)}, combined ${f(ig.vmUtil)}, collapse ${f(ig.collapseUtil)}).`, fin(ig.minWallRequired) ? `Increase the wall to at least ${f(ig.minWallRequired, 1)} mm, raise the grade, or lower the pressure.` : 'Increase the wall thickness or grade, or lower the pressure.', 'A line that meets its code.', 'integ', B.stress.basis, 'pipeline wall thickness design pressure containment collapse', ['integ', 'net']));
    if (fin(ig.upheavalUtil) && ig.upheavalUtil > 1) out.push(R(3, 'Integrity', 'Thermal buckling is expected and must be designed for', `The compressive force from temperature and pressure is ${f(ig.upheavalUtil, 1)} times the buckling resistance of the line as laid.`, 'For an exposed line plan controlled lateral buckling (sleepers, snake-lay or buoyancy at chosen locations); for a buried line provide the cover or rock download given in suite 6.', 'Buckles form where they were designed to, at acceptable strain.', 'integ', 'Hobbs lateral and upheaval buckling screening; a ratio above one means the line will buckle unless restrained, which is normal for hot deep-water flowlines.', 'controlled lateral buckling subsea pipeline sleepers snake lay', ['integ', 'net']));
    if (fin(ig.remainingLife) && ig.remainingLife < F.life) out.push(R(ig.remainingLife < 0.5 * F.life ? 1 : 2, 'Integrity', 'Wall loss will consume the allowance before the end of the project', `Remaining life ${f(ig.remainingLife, 1)} y against ${f(F.life, 0)} y required (corrosion ${f(ig.corrosionRate)} mm/y, erosion ${f(ig.erosionRate, 3)} mm/y).`, 'Improve inhibitor availability, consider a corrosion-resistant alloy for the worst section, and set the inspection interval from the risk-based result' + (fin(ig.inspectionInterval) ? ` (${f(ig.inspectionInterval, 1)} y).` : '.'), 'Avoids a mid-life replacement or a leak.', 'integ', B.corrosion.basis, 'CO2 corrosion carbon steel pipeline inhibitor availability corrosion allowance', ['integ', 'econ']));
    else if (fin(ig.corrosionRate) && ig.corrosionRate > B.corrosion.typical) out.push(R(2, 'Integrity', 'Corrosion rate is above the usual target', `${f(ig.corrosionRate)} mm/y against a managed target of about ${B.corrosion.typical} mm/y.`, 'Review inhibitor efficiency and availability, pH stabilisation where glycol is used, and water wetting.', 'Longer life from the same wall.', 'integ', B.corrosion.basis, 'CO2 corrosion mitigation pH stabilisation inhibitor subsea pipeline', ['integ']));
    if (fin(ig.fatigueLife) && ig.fatigueLife < 10 * F.life && ig.fatigueLife < 1e5) out.push(R(ig.fatigueLife < F.life ? 1 : 2, 'Integrity', 'Slug-induced fatigue governs', `Fatigue life ${f(ig.fatigueLife, 0)} y (damage ${fin(ig.fatigueDamagePerYear) ? ig.fatigueDamagePerYear.toExponential(1) : '–'} per year) before the design fatigue factor.`, 'Add or move supports to raise the natural frequency, improve the weld class at the hot spot, or suppress the slugs.', 'Removes a failure mode that inspection rarely finds in time.', 'integ', 'S–N curves with Palmgren–Miner summation; a design fatigue factor of 3–10 is usual for uninspectable subsea welds.', 'slug induced fatigue subsea jumper spool vibration', ['integ', 'flow']));
    if (fin(ig.fivRatio) && ig.fivRatio > 0.7 && ig.fivRatio < 1.3) out.push(R(1, 'Integrity', 'Slug frequency is close to a structural natural frequency', `Excitation / natural frequency = ${f(ig.fivRatio)} (first mode ${f(ig.naturalFrequency)} Hz).`, 'Change the span or support stiffness so that the first natural frequency is well away from the slug frequency.', 'Avoids resonance and rapid fatigue.', 'integ', 'Resonance occurs near a frequency ratio of one; a separation of at least 30 % is the usual screening rule.', 'flow induced vibration multiphase slug resonance piping natural frequency', ['integ']));
    if (fin(ig.pof) && ig.pof > B.pof.typical) out.push(R(ig.pof > B.pof.poor ? 1 : 2, 'Risk', 'Probability of failure is above the usual target', `${ig.pof.toExponential(1)} per year (reliability index ${f(ig.reliabilityIndex)}); risk level ${ig.riskLevel || '–'}${fin(ig.riskCostPerYear) ? `, expected loss ${M(ig.riskCostPerYear)} per year` : ''}.`, 'Open the sensitivity factors in suite 6: reduce the variable that dominates (usually corrosion-rate uncertainty or wall-thickness knowledge) by inspection or mitigation.', 'Risk reduced where it is cheapest to reduce.', 'integ', B.pof.basis, 'pipeline structural reliability probability of failure risk based inspection', ['integ', 'econ']));
  }
  // ---- economics
  if (ec) {
    if (fin(ec.npv) && ec.npv < 0) out.push(R(1, 'Economics', 'The project does not recover its cost of capital', `Net present value ${M(ec.npv)}${fin(ec.irr) ? `, rate of return ${f(ec.irr, 1)} %/y` : ''}${fin(ec.breakevenPrice) ? `; break-even oil price ${f(ec.breakevenPrice, 0)} $/bbl` : ''}.`, 'Use the tornado chart of suite 7 to find the driver; test the lowest-cost flow-assurance strategy, phasing and a smaller line.', 'A development that can be sanctioned.', 'econ', 'NPV ≥ 0 at the discount rate.', 'subsea tieback economics marginal field development cost', ['econ']));
    else if (fin(ec.breakevenPrice) && F.oilPrice && ec.breakevenPrice > 0.8 * F.oilPrice) out.push(R(2, 'Economics', 'Break-even is close to today’s oil price', `Break-even ${f(ec.breakevenPrice, 0)} $/bbl against Brent at ${f(F.oilPrice, 0)} $/bbl${d.oilPriceDate ? ` (${d.oilPriceDate})` : ''}; one-year range ${f(d.oilPriceMin1y, 0)}–${f(d.oilPriceMax1y, 0)}.`, 'Stress-test with the low-price scenario and the Monte Carlo of suite 7; look at the value of deferring or phasing.', 'A decision that survives a price fall.', 'econ', 'Live Brent spot price (US EIA series).', 'oil price uncertainty real options field development', ['econ']));
    if (fin(ec.probLoss) && ec.probLoss > 0.25) out.push(R(2, 'Economics', 'A loss is a realistic outcome', `Probability of a negative NPV is ${f(100 * ec.probLoss, 0)} % (P90 ${M(ec.npvP90)}, P50 ${M(ec.npvP50)}, P10 ${M(ec.npvP10)}).`, 'Reduce the exposure that drives the downside: firm up cost estimates, phase the investment, or buy information before committing.', 'A narrower range of outcomes.', 'econ', 'Monte Carlo simulation of the cash flow in suite 7.', 'probabilistic economics oil gas project value of information', ['econ']));
    if (ec.bestOption) out.push(R(3, 'Economics', `Lowest lifecycle cost: ${ec.bestOption}`, `Of the flow-assurance strategies compared, “${ec.bestOption}” has the best combined capital, operating and risk cost${Array.isArray(ec.ranking) && ec.ranking[1] ? `; next is “${ec.ranking[1].option}”` : ''}.`, 'Carry this strategy into the design basis and confirm it with the detailed suites (cooldown in 5, deposits in 4).', 'The technically safe option that is also the economic one.', 'econ', 'Lifecycle cost = CAPEX + present value of OPEX + present value of expected failure and deferment cost.', 'flow assurance strategy selection insulation MEG direct electrical heating cost', ['econ', 'ops', 'solids']));
    if (fin(ec.eal) && fin(ec.opexPerYear) && ec.opexPerYear > 0 && ec.eal > 0.25 * ec.opexPerYear) out.push(R(2, 'Risk', 'Expected losses are a large part of operating cost', `Expected annual loss ${M(ec.eal)} against operating cost ${M(ec.opexPerYear)} per year.`, 'Spend on the mitigation with the best ratio of risk reduction to cost; suite 7 optimises the inspection and intervention frequency.', 'Lower total cost of ownership.', 'econ', 'Probability × consequence summed over the failure modes of suite 6.', 'risk based maintenance optimisation offshore pipeline expected loss', ['econ', 'integ']));
  }
  // ---- climate and site context
  const ci = ec?.carbonIntensity;
  if (fin(ci) && ci > B.carbon.typical) out.push(R(2, 'Sustainability', 'Carbon intensity is above the industry average', `${f(ci, 1)} kgCO₂e/boe against about ${B.carbon.typical}${fin(d.carbonPrice) && d.carbonPrice > 0 ? `; the national carbon price is ${f(d.carbonPrice, 0)} $/t` : ''}.`, 'Cut flaring from blowdowns, electrify heating and boosting from a low-carbon supply, and prefer passive insulation over continuous heating or chemical regeneration.', fin(ec?.carbon) ? `Each 10 % cut avoids about ${f(ec.carbon / 10, 0)} tCO₂e a year.` : 'Lower emissions and carbon cost.', 'econ', B.carbon.basis, 'upstream oil gas carbon intensity reduction subsea electrification', ['econ', 'ops']));
  if (F.inhRate && F.boed > 0 && (1000 * F.inhRate) / F.boed > B.chemicals.typical) out.push(R(3, 'Sustainability', 'Chemical use is high', `${f((1000 * F.inhRate) / F.boed, 2)} L of inhibitor per barrel of oil equivalent (${f(F.inhRate, 1)} m³/d).`, 'Compare continuous inhibition with insulation plus treatment only at shutdown, a regeneration loop (for glycol) or a low-dosage inhibitor.', 'Less chemical transport, cost and discharge.', 'econ', B.chemicals.basis, 'low dosage hydrate inhibitor versus MEG methanol consumption environmental', ['ops', 'solids', 'econ']));
  if (fin(d.depth) && d.depth > 0 && fin(nt?.waterDepth) && Math.abs(d.depth - nt.waterDepth) > Math.max(50, 0.25 * nt.waterDepth)) out.push(R(3, 'Data', 'The geometry does not match the site', `Water depth at the selected site is ${f(d.depth, 0)} m but the route in suite 2 reaches ${f(nt.waterDepth, 0)} m.`, 'Apply the site data in suite 2 (or import the surveyed route on the Data portal) and re-run the chain.', 'Hydrostatic head, ambient temperature and collapse checks for the real location.', 'net', 'Site relief from the global elevation model.', 'subsea pipeline route selection bathymetry survey', ['net']));
  if (fin(d.seabedTemp) && fin(nt?.tSeabed) && Math.abs(d.seabedTemp - nt.tSeabed) > 2) out.push(R(3, 'Data', 'Seabed temperature differs from the site value', `The model uses ${f(nt.tSeabed, 1)} °C; the ocean atlas gives ${f(d.seabedTemp, 1)} °C at this location and depth.`, 'Apply the linked site value in suites 2, 3 and 5; cooldown time and hydrate margin depend directly on it.', 'A correct cold boundary for every thermal result.', 'net', 'World Ocean Atlas 2023 annual climatology.', 'seabed temperature deepwater pipeline thermal design', ['net', 'flow', 'ops']));
  if (fin(d.lendingRate) && d.lendingRate > 12) out.push(R(3, 'Economics', 'Local cost of debt is high', `The latest published lending rate is ${f(d.lendingRate, 1)} %/y${d.lendingRateYear ? ` (${d.lendingRateYear})` : ''}.`, 'Capital-light choices (chemicals instead of insulation, phased capacity) weigh more heavily at a high discount rate; test the rate in suite 7.', 'A strategy matched to the real cost of capital.', 'econ', 'World Bank lending interest rate indicator.', 'discount rate capital intensive versus operating cost offshore development', ['econ']));
  return out;
}

/** Ranked recommendations. Pass a suite id to keep only those that concern that suite. */
export function advise(outputs, site, fluid, suiteId) {
  const F = facts(outputs, site, fluid);
  let recs = rules(F);
  if (suiteId) recs = recs.filter((r) => r.suites.includes(suiteId) || r.goTo === suiteId);
  return recs.sort((a, b) => a.priority - b.priority);
}

/** Sustainability scorecard: pillars scored 0–100 from benchmarks, with the evidence behind each. */
export function sustainability(outputs, site, fluid) {
  const F = facts(outputs, site, fluid), { o, d } = F, B = BENCHMARKS, P = [];
  const add = (id, title, sdg, value, unit, s, detail, need) => P.push({ id, title, sdg, value: fin(value) ? value : null, unit, score: s, rating: rate(s), detail, need });
  const ci = o.econ?.carbonIntensity;
  add('climate', 'Climate impact', 'SDG 13', ci, 'kgCO₂e/boe', fin(ci) ? score(ci, B.carbon) : null, fin(ci) ? `${f(o.econ.carbon, 0)} tCO₂e per year in total${fin(d.gridCarbon) ? `; grid electricity ${f(d.gridCarbon)} kgCO₂/kWh` : ''}${fin(d.carbonPrice) ? `; carbon price ${f(d.carbonPrice, 0)} $/t` : ''}.` : '', 'Run the economics suite');
  const kwh = F.boed > 0 && F.power > 0 ? (F.power * 24) / F.boed : F.boed > 0 && (o.ops || o.net) ? 0 : null;
  add('energy', 'Energy efficiency', 'SDG 7', kwh, 'kWh/boe', fin(kwh) ? score(kwh, B.energy) : null, fin(kwh) ? `${f(F.power, 0)} kW of heating, pumping and compression for ${f(F.boed, 0)} boe/d.` : '', 'Run the network and operations suites');
  const chem = F.boed > 0 && fin(F.inhRate) ? (1000 * F.inhRate) / F.boed : null;
  add('chemicals', 'Chemical footprint', 'SDG 12', chem, 'L/boe', fin(chem) ? score(chem, B.chemicals) : null, fin(chem) ? `${f(F.inhRate, 2)} m³/d of hydrate inhibitor.` : '', 'Run the solids or operations suite');
  const pof = o.integ?.pof, sPof = logScore(pof, B.pof), lifeRatio = fin(o.integ?.remainingLife) ? o.integ.remainingLife / F.life : null, sLife = fin(lifeRatio) ? score(lifeRatio, B.life) : null, cont = [sPof, sLife].filter((x) => x !== null);
  add('containment', 'Containment and marine protection', 'SDG 14', pof, 'failures per year', cont.length ? cont.reduce((a, b) => a + b, 0) / cont.length : null, [fin(pof) ? `annual failure probability ${pof.toExponential(1)}` : '', fin(lifeRatio) ? `remaining life ${f(o.integ.remainingLife, 0)} y for ${f(F.life, 0)} y required` : ''].filter(Boolean).join('; '), 'Run the integrity suite');
  add('safety', 'Structural safety margin', 'SDG 9', F.maxUtil, 'highest utilisation', fin(F.maxUtil) ? score(F.maxUtil, B.stress) : null, fin(F.maxUtil) ? `Hoop ${f(o.integ.hoopUtil)}, combined ${f(o.integ.vmUtil)}, collapse ${f(o.integ.collapseUtil)}; risk level ${o.integ.riskLevel || '–'}.` : '', 'Run the integrity suite');
  const up = fin(o.ops?.uptime) ? 100 * o.ops.uptime : null;
  add('resource', 'Resource efficiency (uptime)', 'SDG 12', up, '% uptime', fin(up) ? score(up, B.uptime) : null, fin(up) ? `${fin(o.ops.deferredVolume) ? f(o.ops.deferredVolume, 0) + ' Sm³ of oil deferred per year' : 'Planned and unplanned stops included'}.` : '', 'Run the operations suite');
  const cd = o.ops?.cooldownTime, sRes = [fin(cd) ? score(cd, B.cooldown) : null, fin(F.margin) ? score(F.margin, B.hydrateMargin) : null, o.flow ? (o.flow.severeSlugging ? 10 : o.flow.slug?.type && o.flow.slug.type !== 'none' ? 65 : 100) : null, fin(o.solids?.hydrateRisk) ? 100 * (1 - clamp(o.solids.hydrateRisk, 0, 1)) : null].filter((x) => x !== null);
  add('resilience', 'Operational resilience', 'SDG 9', cd, 'h cooldown', sRes.length ? sRes.reduce((a, b) => a + b, 0) / sRes.length : null, [fin(cd) ? `cooldown ${f(cd, 1)} h` : '', fin(F.margin) ? `hydrate margin ${f(F.margin, 1)} °C` : '', o.flow?.slug?.type ? `slugging: ${o.flow.slug.type}` : '', fin(o.solids?.hydrateRisk) ? `hydrate risk ${f(o.solids.hydrateRisk)}` : ''].filter(Boolean).join('; '), 'Run the flow, solids and operations suites');
  const utc = o.econ?.utc;
  add('value', 'Economic value', 'SDG 8', utc, '$/boe', fin(utc) ? (score(utc, B.utc) + (fin(o.econ.npv) ? (o.econ.npv > 0 ? 100 : 0) : 50)) / 2 : null, fin(utc) ? `NPV ${M(o.econ.npv)}${fin(o.econ.breakevenPrice) ? `, break-even ${f(o.econ.breakevenPrice, 0)} $/bbl` : ''}${F.oilPrice ? ` against Brent ${f(F.oilPrice, 0)} $/bbl` : ''}.` : '', 'Run the economics suite');
  const scored = P.filter((p) => p.score !== null);
  const overall = scored.length ? scored.reduce((a, p) => a + p.score, 0) / scored.length : null;
  return { pillars: P, overall, rating: rate(overall), assessed: scored.length, facts: F };
}
