// HydraSlug service worker (generated by tools/build.mjs — edit tools/sw.template.js, not sw.js).
// Makes the whole application available offline, keeps the last live-data responses for offline
// use, and lets a newer build replace the stored one.
const VERSION = '9e44ea1fb8f7';
const SHELL = 'hydraslug-shell-' + VERSION, DATA = 'hydraslug-data-v1', TILES = 'hydraslug-tiles-v1';
const FILES = ["./","assets/icon-180.png","assets/icon-192.png","assets/icon-512.png","assets/icon-maskable-512.png","assets/icon-maskable.svg","assets/icon.svg","css/app.css","index.html","js/app.js","js/core/advisor.js","js/core/advisorview.js","js/core/bridge.js","js/core/build.js","js/core/caseflow.js","js/core/cfd3d.js","js/core/fmt_acis.js","js/core/fmt_adf.js","js/core/fmt_brep.js","js/core/fmt_cfb.js","js/core/fmt_dgn.js","js/core/fmt_dwg.js","js/core/fmt_e57.js","js/core/fmt_jt.js","js/core/fmt_laz.js","js/core/fmt_s57.js","js/core/fmt_xt.js","js/core/geom.js","js/core/geomlinks.js","js/core/geomview.js","js/core/hdf5.js","js/core/io.js","js/core/live.js","js/core/num.js","js/core/pipe.js","js/core/plot.js","js/core/props.js","js/core/route.js","js/core/run.worker.js","js/core/runner.js","js/core/sqlite.js","js/core/store.js","js/core/suiteview.js","js/core/thermo.js","js/core/ui.js","js/data/app.js","js/data/atlas.js","js/data/atlas_climate.js","js/data/atlas_coast.js","js/data/atlas_codec.js","js/data/atlas_deep.js","js/data/atlas_lookup.js","js/data/atlas_nations.js","js/data/atlas_ocean.js","js/data/atlas_relief.js","js/data/basecase.js","js/data/catalog.js","js/data/changelog.js","js/data/costbasis.js","js/data/deep_lookup.js","js/data/examples.js","js/data/fiscal.js","js/data/fluids.js","js/data/prices.js","js/data/ref/econ.js","js/data/ref/flow.js","js/data/ref/integ.js","js/data/ref/net.js","js/data/ref/ops.js","js/data/ref/pvt.js","js/data/ref/solids.js","js/data/wording.js","js/pages/bridge.js","js/pages/pages.js","js/suites/index.js","js/suites/s01_pvt.js","js/suites/s02_net.js","js/suites/s03_flow.js","js/suites/s04_solids.js","js/suites/s05_ops.js","js/suites/s06_integ.js","js/suites/s07_econ.js","manifest.webmanifest","version.json"];
const DATA_HOSTS = ['api.open-meteo.com', 'marine-api.open-meteo.com', 'geocoding-api.open-meteo.com', 'api.bigdatacloud.net', 'pae-paha.pacioos.hawaii.edu', 'gis.ngdc.noaa.gov', 'erddap.emodnet-physics.eu', 'api.worldbank.org', 'open.er-api.com', 'ourworldindata.org', 'power.larc.nasa.gov', 'api.openalex.org', 'api.crossref.org', 'raw.githubusercontent.com', 'api.eia.gov', 'sdmx.oecd.org', 'api.bls.gov', 'api.imf.org', 'ec.europa.eu', 'stats.bis.org', 'api.db.nomics.world', 'geo.vliz.be'];

const tell = async (msg) => { for (const c of await self.clients.matchAll({ includeUncontrolled: true })) c.postMessage(msg); };

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    // Fetch every file fresh from the network so a new build never mixes with stale HTTP-cached files.
    await Promise.all(FILES.map(async (f) => { const r = await fetch(new Request(f, { cache: 'reload' })); if (!r.ok) throw new Error('precache failed: ' + f); await cache.put(f, r); }));
    if (!self.registration.active) await self.skipWaiting(); // first install: take control immediately
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if ((k.startsWith('hydraslug-shell-') && k !== SHELL) || (k.startsWith('hydraslug-tiles-') && k !== TILES)) await caches.delete(k);
    await self.clients.claim();
    await tell({ type: 'offline-ready' }); await tell({ type: 'version', version: VERSION });
  })());
});

self.addEventListener('message', (e) => {
  if (e.data === 'skipWaiting') self.skipWaiting();
  if (e.data === 'status') caches.has(SHELL).then((ok) => ok && e.source?.postMessage({ type: 'offline-ready' }));
});

async function trim(name, max) { const c = await caches.open(name), keys = await c.keys(); for (let i = 0; i < keys.length - max; i++) await c.delete(keys[i]); }

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin === self.location.origin) {
    if (url.pathname.startsWith('/api/')) return; // shared data feeds of the mirror: always from the network, never from the stored shell
    if (url.pathname.endsWith('/version.json')) { // always ask the network which build is current
      e.respondWith(fetch(req, { cache: 'no-store' }).catch(() => new Response(JSON.stringify({ version: VERSION }), { headers: { 'Content-Type': 'application/json' } })));
      return;
    }
    e.respondWith((async () => {
      const cache = await caches.open(SHELL);
      const hit = (await cache.match(req, { ignoreSearch: true })) || (req.mode === 'navigate' ? await cache.match('index.html') : null);
      if (hit) return hit;
      try { const r = await fetch(req); if (r.ok && r.type === 'basic') cache.put(req, r.clone()); return r; }
      catch { return (await cache.match('index.html')) || Response.error(); }
    })());
    return;
  }
  if (DATA_HOSTS.includes(url.hostname)) { // live data: network first, last good answer when offline
    e.respondWith((async () => {
      const cache = await caches.open(DATA);
      try { const r = await fetch(req); if (r.ok) { cache.put(req, r.clone()); trim(DATA, 60); } return r; }
      catch (err) { const hit = await cache.match(req); if (hit) return hit; throw err; }
    })());
    return;
  }
  if (url.hostname === 'tile.openstreetmap.org' || url.hostname === 'basemaps.cartocdn.com') { // map tiles: stored copy first
    e.respondWith((async () => {
      const cache = await caches.open(TILES), hit = await cache.match(req);
      if (hit) return hit;
      const r = await fetch(req); if (r.ok) { cache.put(req, r.clone()); trim(TILES, 400); } return r; // refused tiles are never stored
    })());
  }
});

// Installed copies on supporting browsers wake up periodically: refresh stored live data and look for a new build.
self.addEventListener('periodicsync', (e) => {
  if (e.tag !== 'refresh') return;
  e.waitUntil((async () => {
    const cache = await caches.open(DATA), keys = await cache.keys();
    await Promise.allSettled(keys.slice(-20).map(async (k) => { const r = await fetch(k.url, { credentials: 'omit' }); if (r.ok) await cache.put(k, r); }));
    await self.registration.update().catch(() => {});
  })());
});
