#!/usr/bin/env python3
"""Builds js/data/atlas_deep.js: annual-mean sea temperature at 12 depths on a 2-degree global grid, from the
NOAA World Ocean Atlas 2023 (objectively analysed climatology, all decades, 1-degree grid, read through the NCEI
OPeNDAP server). The app uses it to give the seabed temperature of any ocean location without a connection.

    python3 tools/atlas_deep.py

Each value is one byte: 0 = no water at this depth, else temperature = -3 + 0.15 * value (deg C)."""
import base64, pathlib, re, sys, time, urllib.request

URL = 'https://www.ncei.noaa.gov/thredds-ocean/dodsC/woa23/DATA/temperature/netcdf/decav/1.00/woa23_decav_t00_01.nc.ascii?t_an%5B0:1:0%5D%5B{k}:1:{k}%5D%5B0:1:179%5D%5B0:1:359%5D'
LEVELS = [(0, 0), (10, 50), (20, 100), (24, 200), (28, 300), (36, 500), (40, 700), (46, 1000), (56, 1500), (66, 2000), (76, 3000), (86, 4000)]  # (index in the 102 standard levels, depth m)

def level(k):
    for attempt in range(4):
        try:
            txt = urllib.request.urlopen(URL.format(k=k), timeout=180).read().decode('ascii', 'replace')
            break
        except Exception as e:
            if attempt == 3: raise
            time.sleep(5)
    rows = []
    for line in txt.splitlines():
        m = re.match(r'^\[0\]\[0\]\[(\d+)\],\s*(.*)$', line)
        if m: rows.append((int(m.group(1)), [float(x) for x in m.group(2).split(',')]))
    rows.sort()
    if len(rows) != 180 or any(len(r[1]) != 360 for r in rows): sys.exit(f'unexpected grid for level {k}: {len(rows)} rows')
    return [r[1] for r in rows]

out = bytearray()
for k, depth in LEVELS:
    g = level(k); n = 0
    for i in range(90):
        for j in range(180):
            vals = [g[2 * i + a][2 * j + b] for a in (0, 1) for b in (0, 1)]
            vals = [v for v in vals if -5 < v < 45]
            if vals: out.append(max(1, min(255, round((sum(vals) / len(vals) + 3) / 0.15)))); n += 1
            else: out.append(0)
    print(f'{depth:5d} m: {n} ocean cells', flush=True)
js = ('// Annual-mean sea temperature at depth on a 2-degree global grid (World Ocean Atlas 2023, objectively analysed\n'
      '// climatology of all decades). Generated by tools/atlas_deep.py. One byte per cell: 0 = no water at this depth,\n'
      '// otherwise temperature = offset + scale * value (deg C). Order: depth level, then latitude (south to north), then\n'
      '// longitude (west to east from 180 W).\n'
      'export const DEEP = { vintage: "World Ocean Atlas 2023 annual climatology", depths: ' + str([d for _, d in LEVELS]) + ', lat0: -89, lon0: -179, step: 2, nlat: 90, nlon: 180, offset: -3, scale: 0.15,\n  data: "' + base64.b64encode(bytes(out)).decode() + '" };\n')
pathlib.Path(__file__).resolve().parent.parent.joinpath('js/data/atlas_deep.js').write_text(js)
print('written', len(js), 'bytes')
