// Writes docs/DATA_SOURCES.md: every bundled reference data set and every checked constant set of the seven suites,
// with citation, address, licence and retrieval date, so that attribution travels with the repository.
//   node tools/sources.mjs
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SUITES, loadSuite } from '../js/suites/index.js';
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
let out = '# Data sources and attribution\n\nGenerated by `tools/sources.mjs` from the suite modules. Reference data sets are compared with the engines on each suite\'s calibration tab; constant sets are listed on each Equations tab.\n';
let nSets = 0, nRows = 0, nProv = 0;
for (const m of SUITES) {
  const s = await loadSuite(m.id), sets = s.validationData || [], prov = s.provenance || [];
  out += `\n## ${m.num}. ${m.title}\n`;
  if (sets.length) {
    out += '\n### Reference data sets\n\n| Data set | Points | Kind | Source | Licence | Read on |\n|---|---|---|---|---|---|\n';
    for (const d of sets) { nSets++; nRows += d.rows.length; out += `| ${esc(d.title)} | ${d.rows.length} | ${esc(d.kind)} | ${esc(d.source?.citation)}${d.source?.url ? ` — <${d.source.url}>` : ''} | ${esc(d.source?.licence)} | ${esc(d.source?.retrieved)} |\n`; }
  }
  if (prov.length) {
    out += '\n### Constants and correlations\n\n| Constant set | Source | Status | Checked on |\n|---|---|---|---|\n';
    for (const p of prov) { nProv++; out += `| ${esc(p.item)} | ${esc(p.source)}${p.url ? ` — <${p.url}>` : ''} | ${esc(p.status)} | ${esc(p.retrieved)} |\n`; }
  }
}
out += `\n---\n${nSets} reference data sets with ${nRows} points; ${nProv} constant sets.\n`;
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '../docs/DATA_SOURCES.md'), out);
console.log(`docs/DATA_SOURCES.md: ${nSets} data sets, ${nRows} points, ${nProv} constant sets`);
